services:
  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=en_US-hfc_male-medium
      - PIPER_LENGTH=1.0 # optional
      - PIPER_NOISE=0.667 # optional
      - PIPER_NOISEW=0.333 # optional
      - PIPER_SPEAKER=0 # optional
      - PIPER_PROCS=1 # optional
    volumes:
      # - /path/to/piper/data:/config
      - ./piper_models:/usr/share/piper_models # Volume for Piper models
    ports:
      - 10200:10200
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'nc -z localhost 10200']
      interval: 10s
      timeout: 5s
      retries: 5

  epub_to_audiobook:
    build:
      context: ./ # Directory containing the Dockerfile for epub_to_audiobook
      dockerfile: Dockerfile # Name of the Dockerfile (if it's not the default 'Dockerfile')
    container_name: epub_to_audiobook
    environment:
      - PIPER_HOST=piper
      - PIPER_PORT=10200
    volumes:
      - ./:/app
      - /Users/allennikka/Calibre Library:/calibre_library # Map the Calibre Library directory
    # command: tail -f /dev/null # Uncomment this line to keep the container running, and run via connecting to it with `docker exec -it epub_to_audiobook /bin/bash`
    command: "python main.py --tts piper_docker --no_prompt '/calibre_library/Eliezer Yudkowsky/Harry Potter and the Methods of Rationality (20)/Harry Potter and the Methods of Rationalit - Eliezer Yudkowsky.epub' audiobook_output --chapter_start 5 --chapter_end 5" # Run command directly
    depends_on:
      piper:
        condition: service_healthy
